apiVersion: batch/v1
kind: Deployment
metadata:
  name: archive-everything-archiver
  namespace: archive-everything
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: archive-everything-archiver
        replicas: 1
        image: archive-everything/archiver:latest
        command: ["python",  "main.py"]
        envFrom:
          - configMapRef:
              name: archive-everything-archiver-cfg
          - secretRef:
              name: archive-everything-archiver-secret
  backoffLimit: 4
