apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-everything-archiver-deploy
  namespace: archive-everything
spec:
  selector:
    matchLabels:
      app: archiver
  replicas: 1
  template:
    spec:
      metadata:
        labels:
          app: archiver
      containers:
      - name: archiver-pods
        port: 50001
        image: archive-everything/archiver:latest
        command: ["python",  "main.py"]
        envFrom:
          - configMapRef:
              name: archive-everything-archiver-cfg
          - secretRef:
              name: archive-everything-archiver-secret
