apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-everything-archiver-deploy
  namespace: archive-everything
spec:
  selector:
    matchLabels:
      app: archiver
  replicas: 1
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      labels:
        app: archiver
    spec:
      containers:
      - name: archiver-pods
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        image: archive-everything-archiver:126
        command: ["python",  "main.py"]
        ports:
          - containerPort: 50051
        envFrom:
          - configMapRef:
              name: archive-everything-archiver-cfg
          - secretRef:
              name: archive-everything-archiver-secret
