apiVersion: apps/v1
kind: Deployment
metadata:
  name: archive-everything-archiver-deploy
  namespace: archive-everything
spec:
  selector:
    matchLabels:
      app: archiver
  replicas: 1
  template:
    metadata:
      labels:
        app: archiver
    spec:
      containers:
      - name: archiver-pods
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        image: archive-everything-archiver:125
        command: ["python",  "main.py"]
        envFrom:
          - configMapRef:
              name: archive-everything-archiver-cfg
          - secretRef:
              name: archive-everything-archiver-secret
